// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo7ZEAFw3p0-fS_05KP5mZJdYYeUkBgr8',
    appId: '1:567717107287:web:792df77f19765edc0af512',
    messagingSenderId: '567717107287',
    projectId: 'my-budget-app-c6fa8',
    authDomain: 'my-budget-app-c6fa8.firebaseapp.com',
    storageBucket: 'my-budget-app-c6fa8.firebasestorage.app',
    measurementId: 'G-0DXCY379CR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_tGialu7VemIOdDoxrCSAznjwmXI7gTI',
    appId: '1:567717107287:android:6633da33734108cd0af512',
    messagingSenderId: '567717107287',
    projectId: 'my-budget-app-c6fa8',
    storageBucket: 'my-budget-app-c6fa8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGEbB2pAhz0sJy3UFC7cjF5gc6bhA3a0s',
    appId: '1:567717107287:ios:2000262ff9e9d55d0af512',
    messagingSenderId: '567717107287',
    projectId: 'my-budget-app-c6fa8',
    storageBucket: 'my-budget-app-c6fa8.firebasestorage.app',
    iosBundleId: 'com.example.budgetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGEbB2pAhz0sJy3UFC7cjF5gc6bhA3a0s',
    appId: '1:567717107287:ios:2000262ff9e9d55d0af512',
    messagingSenderId: '567717107287',
    projectId: 'my-budget-app-c6fa8',
    storageBucket: 'my-budget-app-c6fa8.firebasestorage.app',
    iosBundleId: 'com.example.budgetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo7ZEAFw3p0-fS_05KP5mZJdYYeUkBgr8',
    appId: '1:567717107287:web:9f7d8dd473bdaca60af512',
    messagingSenderId: '567717107287',
    projectId: 'my-budget-app-c6fa8',
    authDomain: 'my-budget-app-c6fa8.firebaseapp.com',
    storageBucket: 'my-budget-app-c6fa8.firebasestorage.app',
    measurementId: 'G-XCM7N507SF',
  );
}
